#!/usr/bin/env python3
"""
os_current_state_boot.py , load CURRENT STATE FIRST before any strategy/build/audit/money/tool/MAX claim.

Loads the 12 boot artifacts in order, stamps each with last-modified, compares against the latest git
commit time, and flags any boot artifact OLDER than the newest commit as POSSIBLY STALE (newest committed
truth wins). Writes OS_BOOT_REPORT.md. Exits nonzero if a REQUIRED boot artifact is missing.

  os_current_state_boot.py            , run boot, write OS_BOOT_REPORT.md
  os_current_state_boot.py --quiet    , write report, minimal stdout
"""
import os, sys, subprocess, datetime
HERE=os.path.dirname(os.path.abspath(__file__)); CMD=os.path.dirname(HERE); REPO=os.path.dirname(CMD)
def P(*a): return os.path.join(CMD,*a)

# (order, label, path, required?)
BOOT=[
 (1,"current_state",        P("OS_CURRENT_STATE.md"), True),
 (2,"next_action",          P("NEXT_ACTION.md"), True),
 (3,"git_log",              None, True),  # special
 (4,"capability_dashboard", P("OS_CAPABILITY_COVERAGE_MATRIX.md"), True),
 (5,"tool_registry",        os.path.join(HERE,"os_tool_registry.py"), True),
 (6,"starthere_dashboard",  P("OS_STARTHERE_OPERATIONALIZATION_DASHBOARD.md"), True),
 (7,"technique_card_store", P("TECHNIQUE_CARDS.json"), True),
 (8,"library_loader",       os.path.join(HERE,"os_library.py"), True),
 (9,"premium_stack_std",    P("OS_PREMIUM_STACK_STANDARD.md"), True),
 (10,"money_router_state",  P("OS_GRAND_MONEY_PLAY_DECISION_ANSWER.md"), True),
 (11,"failure_ledger",      P("OS_FAILURE_LEDGER.csv"), True),
 (12,"stale_ledger",        P("OS_STALE_ASSUMPTION_LEDGER.csv"), True),
]

def git(*args):
    try: return subprocess.run(["git","-C",REPO]+list(args),capture_output=True,text=True,timeout=20).stdout.strip()
    except Exception as e: return f"(git error: {e})"

def mtime(p):
    try: return datetime.datetime.fromtimestamp(os.path.getmtime(p))
    except: return None

def main(quiet=False):
    head=git("log","-1","--format=%H|%ci|%s")
    commit_hash=commit_time=commit_subj=None
    last_commit_dt=None
    if "|" in head:
        commit_hash,commit_iso,commit_subj=head.split("|",2)
        try: last_commit_dt=datetime.datetime.fromtimestamp(int(git("log","-1","--format=%ct")))
        except: last_commit_dt=None
    recent=git("log","-8","--format=%h %ci %s")

    L=["# OS Boot Report , CURRENT STATE FIRST",""]
    L.append(f"Generated by os_current_state_boot.py. Newest committed truth wins.")
    L.append("")
    L.append(f"## Latest commit\n- `{commit_hash}` , {commit_subj}\n- at {commit_iso if commit_hash else '?'}")
    L.append("")
    L.append("## Recent commits (last 8)")
    for ln in recent.splitlines(): L.append(f"- {ln}")
    L.append("")
    L.append("## Boot artifacts (load order)")
    missing=[]; stale=[]
    for order,label,path,req in BOOT:
        if label=="git_log":
            L.append(f"{order}. **{label}** , loaded (HEAD {commit_hash[:9] if commit_hash else '?'})"); continue
        if not path or not os.path.exists(path):
            tag="MISSING (REQUIRED)" if req else "missing (optional)"
            L.append(f"{order}. **{label}** , {tag} , `{os.path.relpath(path,REPO) if path else '?'}`")
            if req: missing.append(label)
            continue
        mt=mtime(path); rel=os.path.relpath(path,REPO)
        flag=""
        if last_commit_dt and mt and mt < last_commit_dt - datetime.timedelta(hours=2):
            flag="  <-- POSSIBLY STALE (older than latest commit)"; stale.append((label,rel,mt))
        L.append(f"{order}. **{label}** , {mt:%Y-%m-%d %H:%M} , `{rel}`{flag}")
    L.append("")
    # live status snapshots
    L.append("## Live snapshots")
    def run(cmd):
        try: return subprocess.run(cmd,cwd=HERE,capture_output=True,text=True,timeout=30).stdout.strip()
        except Exception as e: return f"(error: {e})"
    L.append("### Tool registry dashboard")
    L.append("```\n"+run(["python3","os_tool_registry.py","dashboard"])+"\n```")
    L.append("### Library store")
    L.append("```\n"+run(["python3","os_library.py","list"])+"\n```")
    L.append("### Stale-assumption ledger (open risks)")
    L.append("```\n"+run(["python3","os_stale_assumption_gate.py","audit"])+"\n```")
    L.append("")
    L.append("## BOOT VERDICT")
    if missing: L.append(f"- BOOT INCOMPLETE , missing required: {', '.join(missing)}")
    else: L.append("- all 12 required boot artifacts present.")
    if stale:
        L.append("- POSSIBLY STALE artifacts (refresh before trusting; newest commit wins):")
        for lab,rel,mt in stale: L.append(f"  - {lab} ({rel}, {mt:%Y-%m-%d})")
    else:
        L.append("- no boot artifact is older than the latest commit.")
    L.append("")
    L.append("Next: run os_tool_reality_check.py for the task's tools, os_stale_assumption_gate.py on any claim, and os_max_readiness_gate.py before any MAX/ELITE/COMPLETE/READY call.")
    out=P("OS_BOOT_REPORT.md"); open(out,"w").write("\n".join(L)+"\n")

    if not quiet:
        print(f"BOOT , latest commit {commit_hash[:9] if commit_hash else '?'} : {commit_subj}")
        print(f"boot artifacts present: {12-len(missing)}/12" + (f"  MISSING: {', '.join(missing)}" if missing else ""))
        if stale: print("POSSIBLY STALE: "+", ".join(l for l,_,_ in stale))
        print(f"report -> {out}")
    return 1 if missing else 0

if __name__=="__main__":
    sys.exit(main(quiet="--quiet" in sys.argv))
