#!/usr/bin/env python3
"""
os_starthere_dashboard.py , generates OS_STARTHERE_OPERATIONALIZATION_DASHBOARD.md from live state.

Reads the classification CSV + the live card store + the libraries, recomputes per-doc card coverage,
and writes the scoreboard. Re-run any time to refresh; never hand-edited.

  os_starthere_dashboard.py
"""
import os, csv, json, re, importlib.util, glob
HERE=os.path.dirname(os.path.abspath(__file__)); CMD=os.path.dirname(HERE)
def _imp(n):
    spec=importlib.util.spec_from_file_location(n, os.path.join(HERE,n+".py"))
    m=importlib.util.module_from_spec(spec); spec.loader.exec_module(m); return m
LIB=_imp("os_library"); CARDS=LIB.CARDS
CSV=os.path.join(CMD,"OS_STARTHERE_OPERATIONALIZATION.csv")
OUT=os.path.join(CMD,"OS_STARTHERE_OPERATIONALIZATION_DASHBOARD.md")

def norm(s):
    s=(s or "").lower().split("/")[-1]; s=re.sub(r"\.(txt|docx)$","",s); return re.sub(r"\s+"," ",s).strip()
from collections import Counter
cardsrc=Counter(norm(c.get("source_doc") or c.get("source","")) for c in CARDS)
def cards_for(doc):
    nd=norm(doc); n=cardsrc.get(nd,0)
    if n==0:
        for k,v in cardsrc.items():
            if k and len(k)>5 and (k in nd or nd in k): return v
    return n

rows=list(csv.DictReader(open(CSV)))
status=Counter(r["conversion_status"] for r in rows)
# a doc counts as converted if it now has >=1 callable card in the store
converted=[]; not_converted=[]
for r in rows:
    if r["conversion_status"] in ("DISCARD","QUEUE"): continue
    (converted if cards_for(r["doc"])>0 else not_converted).append(r)
# library counts
libcounts={lib:len(LIB.cards_in(f)) for lib,f in LIB.LIBRARIES.items()}
prompt_templates=sum(1 for c in CARDS if c.get("prompt_pattern"))
gate_scripts=sorted(os.path.basename(p) for p in glob.glob(os.path.join(HERE,"os_*gate*.py")))
routes=len(LIB.PROJECTS)

L=[]
L.append("# OS Start Here Operationalization Dashboard")
L.append("")
L.append("Generated by os_starthere_dashboard.py from live state. Not hand-edited. Re-run to refresh.")
L.append("")
L.append("## Totals")
L.append(f"- Total Start Here docs: **{len(rows)}**")
L.append(f"- USE (target for cards): {status.get('USE',0)}   |   USED (already carded): {status.get('USED',0)}")
L.append(f"- QUEUED (with reason): {status.get('QUEUE',0)}   |   DISCARDED (dup/low-signal): {status.get('DISCARD',0)}")
L.append(f"- Docs CONVERTED (>=1 callable card): **{len(converted)}**")
L.append(f"- Docs still NOT converted (USE/USED with 0 cards): **{len(not_converted)}**")
L.append("")
L.append("## Cards extracted (the one store)")
L.append(f"- Total callable technique cards: **{len(CARDS)}**")
L.append(f"- Reusable prompt templates among them: {prompt_templates}")
L.append("")
L.append("## Operator libraries (views over the store)")
for lib,n in libcounts.items(): L.append(f"- {lib}: {n} cards")
L.append("")
L.append("## Gates created")
for g in gate_scripts: L.append(f"- {g}")
L.append("")
L.append(f"## Routes created\n- {routes} project-type loadouts: {', '.join(LIB.PROJECTS)}")
L.append("- front door: os_ask.py (card + source + library + gate + next action)")
L.append("")
L.append("## Docs still NOT converted (highest-leverage remaining, by words)")
nc=sorted(not_converted, key=lambda r:-int(r["words"]))
if not nc: L.append("- none. every USE/USED doc has at least one callable card.")
for r in nc[:25]:
    L.append(f"- [{r['conversion_status']}] {r['doc']} ({int(r['words']):,} words, {r['primary_family']})")
L.append("")
L.append("## Discarded (with reason)")
for r in rows:
    if r["conversion_status"]=="DISCARD": L.append(f"- {r['doc']} , {r['reason']}")
L.append("")
L.append("## Queued (with reason)")
for r in rows:
    if r["conversion_status"]=="QUEUE": L.append(f"- {r['doc']} , {r['reason']}")
L.append("")
open(OUT,"w").write("\n".join(L)+"\n")
print(f"wrote {OUT}")
print(f"docs converted: {len(converted)}  not converted: {len(not_converted)}  cards: {len(CARDS)}")
