#!/usr/bin/env bash
# Reverse Step 3 (run from repo root). All three dirs were untracked -> plain mv back.
# NOTE: top-level OS_V2_UNIVERSAL_ENGINE/ was never moved; do not touch it.
set -e
mv 00_COMMAND_CENTER/_HISTORY/OS_CONTENT_ENGINE_001 00_COMMAND_CENTER/OS_CONTENT_ENGINE_001
mv 00_COMMAND_CENTER/_HISTORY/OS_V2_UNIVERSAL_ENGINE_001 00_COMMAND_CENTER/OS_V2_UNIVERSAL_ENGINE_001
mv 00_COMMAND_CENTER/_HISTORY/OS_REFINERY_AUTONOMY_001 00_COMMAND_CENTER/OS_REFINERY_AUTONOMY_001
